### ISSUE TITLE
Incorrect request_params for username-password login

### ISSUE THREAD

**Issue by mmaddex** [auth0/ruby-auth0#109]
This is preventing callers from passing `audience` and `realm` along.

There seem to be a few things that could be addressed here:

- This should include `audience` and `realm`
- Remove old `/oauth/ro` params: `connection`, `id_token`, and `device`
- the default `grant_type` should be `'password'` not `password`

https://github.com/auth0/ruby-auth0/blob/687326f7c81db114a1ff8de2047c8974fa461247/lib/auth0/api/authentication_endpoints.rb#L59-L70

**Comment by gastonrey** [comment]
Am having problems to login via user/password due to the deprecated 'Connection' key, it's now `realm`, so I have changed the login method to:

```
request_params = { 
   client_id:     @client_id, 
   client_secret: @client_secret, 
   username:      username, 
   password:      password, 
   scope:            options.fetch(:scope, 'openid'), 
   realm:            connection_name, 
   grant_type:    options.fetch(:grant_type, 'password'), 
   id_token:      id_token, 
   device:        options.fetch(:device, nil) 
 } 
```
Replaced `connection` key by `realm`.

And then at my login request the `grant-type` is supposed to be passed as:

```
grant_type: 'http://auth0.com/oauth/grant-type/password-realm'
```
Just inside the `options` object. Would probably be a good idea to leave it as the default value when user/password login.

**Comment by joshcanhelp** [comment]
Apologies for the late reply here ... the auth endpoints module in this SDK is getting an overhaul for the next release. We'll be deprecating (not removing yet) a few methods, this one included, and replacing with ones that more closely match how the endpoints work currently. All of the concerns here will be addressed. 

Thank you for the report!

**Comment by j-collier** [comment]
> We'll be deprecating (not removing yet) a few methods, this one included, and replacing with ones that more closely match how the endpoints work currently. All of the concerns here will be addressed.

Are the plans for this public? I'd love to help tackle this personally.

**Comment by joshcanhelp** [comment]
@j-collier - I appreciate the offer! The plans are not public but only because our tracking is done in the same system as our product. Happy to share what we have in mind remaining.

Much of this is complete, some of which has already been merged:

- #129 (merged) adds a formal client credentials grant
- #130 (merged) adds a `/userinfo` call that works (have to include an access token)
- #131 (in review) will add a method to perform an authorization code exchange
- #133 (in review) will add a method that does a more complete resource owner grant

The remaining methods that have not been started:

- A method to replace `authorization_url` ... current one works but could be structured better. It should also generate a state automatically. Replace with a method that does both and adds audience as a first-class parameter.
- A method to use a refresh token to get a new access token. 

If you want to take on one of those, I would be happy to guide and review! At the moment, we don't have a contribution guide (on my list to put one of those together soon) but a few notes:

- Make sure to add unit tests to [`spec/lib/auth0/api/authentication_endpoints_spec.rb`](https://github.com/auth0/ruby-auth0/blob/master/spec/lib/auth0/api/authentication_endpoints_spec.rb). You can run those with `bundle exec rake spec`
- Where possible, make sure to add integration tests to [`spec/integration/lib/auth0/api/api_authentication_spec.rb`](https://github.com/auth0/ruby-auth0/blob/master/spec/integration/lib/auth0/api/api_authentication_spec.rb). You can run those with `MODE=full bundle exec rake all`. Note that we recently added VCR HTTP recording to the suite (#132) so uncomment [this line](https://github.com/auth0/ruby-auth0/blob/master/spec/spec_helper.rb#L9) and leave VCR off when you're writing the tests, then add VCR, run twice, and add that comment back. We've got [filtering in place](https://github.com/auth0/ruby-auth0/blob/master/spec/spec_helper.rb#L13) to remove sensitive data but make sure to review the YML files created before pushing. 

If you want to take one or the other or both (separate PRs please), just let me know and I'll hold off on my end. I'll work on the contribution guide instead 😄 

Thank you in advance!!
