### ISSUE TITLE
Unable to set audience

### ISSUE THREAD

**Issue by rally25rs** [auth0/ruby-auth0#189]
### Description

When initializing the client, the `audience` cannot be set.

If you try to use the default `Auth0 Management API` system api against a custom domain, you have to specify an `audience` that is different than the `domain`. You are currently unable to do this.

### Prerequisites

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] Did you check the documentation ([repo README](https://github.com/auth0/ruby-auth0/blob/master/README.md) or [Quickstart](https://auth0.com/docs/quickstart/backend/rails))?
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository? See also the [OmniAuth-Auth0 strategy](https://github.com/auth0/omniauth-auth0) for logging in with Rails.
* [x] Are there any related or duplicate [Issues](https://github.com/auth0/ruby-auth0/issues) or [PRs](https://github.com/auth0/ruby-auth0/pulls) for this issue?

### Environment

Please provide the following:

* Ruby Auth0 version: current `master` at the time of issue creation (`4.8.0`?)
* Ruby version:
* Rails version (if applicable):
* Browser version (if applicable):
* Additional gems that might be affecting your instance

### Reproduction

The code (which tries to pass an audience):
```
Auth0Client.new(
          client_id: '...',
          client_secret: '...',
          domain: 'accounts.my-org.com',
          audience: 'https://my-org.auth0.com/api/v2/',
          api_version: 2
```
results in the request body:
```
{
  "grant_type":"client_credentials",
  "client_id":"...",
  "client_secret":"...",
  "audience":"https://accounts.my-org.com/api/v2/"
}
```

The `audience` appears to be built based on the `domain` with no way to override it.

**Comment by joshcanhelp** [comment]
@rally25rs - I'm guessing that you're using the built-in client credentials grant to get an API token for management API calls, is that correct? So initializing `Auth0::Client` without a manually-generated token?

If so, you have two options ... you can extend `Auth0::Api::AuthenticationEndpoints` and call the `api_token` method directly with in an `audience` there:

https://github.com/auth0/ruby-auth0/blob/master/lib/auth0/api/authentication_endpoints.rb#L14

... then initialize `Auth0::Client` with the access token you get back instead of relying on the default call. Alternatively, you can use a separate `Auth0::Client` instance for Management API calls. 

Will one of those two options work for you? Or do you think it's worth it to add another item to the config hash for a custom domain?

**Comment by rally25rs** [comment]
> using the built-in client credentials grant to get an API token for management API calls, is that correct?

Yes that is what we had been trying to do. In the end we just resolved this by not using our custom `cname` as the `domain`.

So I guess it isn't much of a priority, it just seems like with the ability to provide a custom domain name in the Auth0 tenant configuration, it'd be nice to actually be able to use it :) but it ended up not being a big deal once we realized what was going on. My opinion is that since there is no reason why the `domain` and `audience` have to match, that they should be configurable, but it isn't blocking us from using this gem at the moment.

**Comment by joshcanhelp** [comment]
> My opinion is that since there is no reason why the domain and audience have to match

I definitely agree. We want to make sure that our SDKs make it easy to use the features that our core product provides. In this case, it's possible to do that using one of the two options above but maybe that's too complicated to be useful? 

Either way, I think we can improve how this works so I'll leave this open for now to figure out the best way to do that.

**Comment by zinosama** [comment]
@joshcanhelp how do you feel about supporting an additional option `:audience` in the initializer? And then call `... = api_token(audience: @audience).token ...` from `#initialize_v2`? I can open a PR for that if that's reasonable.

**Comment by joshcanhelp** [comment]
@zinosama - That _might_ work but we would need to somehow disambiguate what we meant by `audience` there. Since the Auth0 client can generate login URLs (where `audience` would indicate the API that the Ruby application is requesting an access token for on behalf of the user) as well as make management calls (where `audience` is the Management API base URL), that might be confusing. 

I think maybe a better route here would be to ask for `:custom_domain` and sub that in for authentication calls. 

Thoughts on that @rally25rs ?
