### ISSUE TITLE
IOError: closed stream - Retryable incompatible with users-import endpoint

### ISSUE THREAD

**Issue by victorpugin** [auth0/ruby-auth0#312]
### Describe the problem

When reaching [the rate limiting of 2 concurrent jobs](https://auth0.com/docs/manage-users/user-migration/bulk-user-imports#concurrent-import-jobs) importing users on Auth0, `import_users` raises the error `IOError: closed stream` on the first retry.

The gem `restclient` is closing the IO stream in `lib/restclient/payload.rb:192` at the end of the `send_file` method. Retryable triggers the `send_file` method again, but the stream is already closed.

```
IOError: closed stream
  from delegate.rb:349:in `read'
  from delegate.rb:349:in `block in delegating_block'
  from rest-client (2.1.0) lib/restclient/payload.rb:188:in `create_file_field'
  from rest-client (2.1.0) lib/restclient/payload.rb:162:in `block in build_stream'
  from rest-client (2.1.0) lib/restclient/payload.rb:159:in `each'
  from rest-client (2.1.0) lib/restclient/payload.rb:159:in `each_with_index'
  from rest-client (2.1.0) lib/restclient/payload.rb:159:in `build_stream'
  from rest-client (2.1.0) lib/restclient/payload.rb:61:in `initialize'
  from rest-client (2.1.0) lib/restclient/payload.rb:24:in `new'
  from rest-client (2.1.0) lib/restclient/payload.rb:24:in `generate'
  from rest-client (2.1.0) lib/restclient/request.rb:88:in `initialize'
  from rest-client (2.1.0) lib/restclient/request.rb:63:in `new'
  from rest-client (2.1.0) lib/restclient/request.rb:63:in `execute'
  from ruby-auth0 (cc794c0c76ab) lib/auth0/mixins/httpproxy.rb:109:in `call'
  from ruby-auth0 (cc794c0c76ab) lib/auth0/mixins/httpproxy.rb:91:in `request'
  from ruby-auth0 (cc794c0c76ab) lib/auth0/mixins/httpproxy.rb:69:in `block in request_with_retry'
  from retryable (3.0.5) lib/retryable.rb:72:in `retryable'
  from ruby-auth0 (cc794c0c76ab) lib/auth0/mixins/httpproxy.rb:68:in `request_with_retry'
  from ruby-auth0 (cc794c0c76ab) lib/auth0/mixins/httpproxy.rb:23:in `block (2 levels) in <module:HTTPProxy>'
  from ruby-auth0 (cc794c0c76ab) lib/auth0/api/v2/jobs.rb:53:in `import_users'
```

### What was the expected behavior?

The gem should retry the call `send_file` 3 times then raise the error `Auth0::RateLimitEncountered`.

The following patch in `lib/auth0/mixins/httpproxy.rb:67` makes possible to reproduce the expected behavior with some logs to check that retries are correctly done : 
```
def request_with_retry(method, uri, body = {}, extra_headers = {})
  log_method = lambda do |retries, exception|
    Logger.new(STDOUT).debug("[Attempt ##{retries}] Retrying because [#{exception.class} - #{exception.message}]: #{exception.backtrace.first(5).join(' | ')}")
  end
  Retryable.retryable(retry_options.merge(log_method: log_method)) do
    if method == :post_file && uri == "/api/v2/jobs/users-imports"
      body[:users] = File.open(body[:users])
    end

    request(method, uri, body, extra_headers)
  end
end
```

### Reproduction

Call 3 times `import_users` with a file of suffisent size to take a few seconds to process on Auth0, the 3rd call is going to fail with `IOError: closed stream`.

### Environment

- **Version of this library used:** 5.6.1
- **Other modules/plugins/libraries that might be involved:** rest-client (2.1), retryable (3.0)

cc @benoittgt

**Comment by benoittgt** [comment]
Hello

We wrote a workaround for this on one of our app but this something the gem should handle. @stevehobbsdev do you think something could be done?

**Comment by stevehobbsdev** [comment]
First of all thanks for your patience here, I appreciate I've dropped the ball with responding just while focussing on other priorities.

Are you able to share the workaround in some form @benoittgt, or is it very specific your app and not really relevant here?

**Comment by kwstannard** [comment]
@stevehobbsdev I think the best option is to read the rate limit headers and decide when to send the next request based off of those.

**Comment by will-in-wi** [comment]
Could this be re-opened and fixed? I just wasted a few hours on this. I think this is a sharp edge on the `import_users` method when you don't notice that the documentation only allows two simultaneous, running jobs. When you try to send the third job, it fails, and then attempts to retry by generating the request object again. But, as described in the OP, it fails to re-traverse the file IO object since it closed it.

The real solution is to not send more than two simultaneous jobs at once. But that's easy to miss, and the error message misleads you.

A couple of suggested solutions:
- Consider whether to not close the file IO object. Depending on what exactly you are expecting to be passed, it might still need to be used by the code after the request, so closing it might actually make life harder for the other code (although this seems unlikely in regular usage).
- As a general rule, whenever you retry, hang on to the first error and when retrying finally fails, return the first error instead of or in addition to the last error. This would avoid this and other issues where the very act of retrying causes issues.
- Perhaps update the internal API to accept a string instead of (or in addition to) a file pointer. I was hacking together a StringIO object to avoid having to stick files on disk just to send them.
- Consider building a new method where you can pass in a large array of user data to import and the gem will automatically chunk it up into 500KB chunks and send them, monitoring to only send two at once (basically solving the code we're writing in the first place). Or use blocks to make it lazier. Or both!
