### ISSUE TITLE
I want to generate clients without having to set up credentials in the source code.

### ISSUE THREAD

**Issue by tetsuya-ogawa** [auth0/ruby-auth0#322]
### Describe the problem you'd like to have solved

I want to generate clients without having to set up credentials in the source code.

### Describe the ideal solution

I want to refer to the environment variable if it is set with authentication information.

e.g
AUTH0_CLIENT_ID=xxxxx
AUTH0_CLIENT_SECRET=xxxxx
AUTH0_DOMAIN=xxxxx

### Additional information, if any

For example, how about changing the following code part as follows

```ruby
@client_id = options[:client_id] || ENV['AUTH0_CLIENT_ID']
```

https://github.com/auth0/ruby-auth0/blob/master/lib/auth0/mixins/initializer.rb#L20

**Comment by stevehobbsdev** [comment]
Thanks for the suggestion. Rather than us supporting environment variables directly in the library, you could instead pass an environment variable when you set up the client from within your own application.

e.g:

```ruby
Auth0Client.new client_id: ENV['AUTH0_CLIENT_ID'], client_secret: ENV['AUTH0_CLIENT_SECRET']
```

I feel this is a reasonable alternative to your suggestion so will close this for now. However, happy to continue the conversation if there's something I'm missing.
